// scripts/deploy.js
// Deploy StreamPay contracts to Somnia Testnet
// Usage: npx hardhat run scripts/deploy.js --network somnia
// Requires: PRIVATE_KEY set in contracts/.env

require("dotenv").config();
const { writeFileSync, existsSync, mkdirSync } = require("fs");
const { join } = require("path");

async function main() {
  console.log("\n🚀 StreamPay — Deployment to Somnia Testnet\n");

  // Validate private key
  if (!process.env.PRIVATE_KEY || process.env.PRIVATE_KEY.trim() === "") {
    throw new Error(
      "PRIVATE_KEY is not set.\n" +
      "→ Open contracts/.env and fill in your deployer private key.\n" +
      "→ Example: PRIVATE_KEY=0xYOUR_PRIVATE_KEY_HERE"
    );
  }

  // Use hre.viem provided by @nomicfoundation/hardhat-toolbox-viem
  const hre = require("hardhat");

  // Get the deployer wallet client
  const [deployer] = await hre.viem.getWalletClients();
  const deployerAddress = deployer.account.address;

  const publicClient = await hre.viem.getPublicClient();
  const balance = await publicClient.getBalance({ address: deployerAddress });

  console.log("Deployer  :", deployerAddress);
  console.log("Network   :", hre.network.name);
  console.log("Chain ID  :", hre.network.config.chainId);
  console.log("Balance   :", (Number(balance) / 1e18).toFixed(6), "STT\n");

  if (balance === 0n) {
    console.warn(
      "⚠️  Deployer balance is 0. Get testnet STT from the Somnia faucet before deploying.\n" +
      "   Faucet: https://testnet.somnia.network/faucet\n"
    );
  }

  // ─── Deploy StreamPay ─────────────────────────────────────────────────────
  console.log("📋 Deploying StreamPay...");
  const streamPay = await hre.viem.deployContract("StreamPay", [deployerAddress]);
  await publicClient.waitForTransactionReceipt({ hash: streamPay.deploymentTransaction?.hash ?? "0x" });
  console.log("✅ StreamPay deployed at:", streamPay.address);

  // ─── Deploy StreamKeeper ──────────────────────────────────────────────────
  console.log("\n📋 Deploying StreamKeeper...");
  const streamKeeper = await hre.viem.deployContract("StreamKeeper", [streamPay.address]);
  console.log("✅ StreamKeeper deployed at:", streamKeeper.address);

  // ─── Deploy StreamFactory ─────────────────────────────────────────────────
  console.log("\n📋 Deploying StreamFactory...");
  const streamFactory = await hre.viem.deployContract("StreamFactory", [streamPay.address]);
  console.log("✅ StreamFactory deployed at:", streamFactory.address);

  // ─── Summary ──────────────────────────────────────────────────────────────
  const deploymentData = {
    streamPay: streamPay.address,
    streamKeeper: streamKeeper.address,
    streamFactory: streamFactory.address,
    network: hre.network.name,
    chainId: hre.network.config.chainId,
    deployer: deployerAddress,
    timestamp: new Date().toISOString(),
    explorer: `https://shannon-explorer.somnia.network/address/${streamPay.address}`,
  };

  console.log("\n────────────────────────────────────────────────");
  console.log("🎉 Deployment Complete!\n");
  console.log(JSON.stringify(deploymentData, null, 2));
  console.log("────────────────────────────────────────────────\n");

  // ─── Write .env.local for the frontend ────────────────────────────────────
  const envLocalPath = join(__dirname, "../../streampay/.env.local");
  const envContent = [
    `# Auto-generated by deploy.js on ${new Date().toISOString()}`,
    `# Network: ${hre.network.name} (Chain ID ${hre.network.config.chainId})`,
    ``,
    `NEXT_PUBLIC_STREAMPAY_ADDRESS=${streamPay.address}`,
    `NEXT_PUBLIC_STREAM_PAY_ADDRESS=${streamPay.address}`,
    `NEXT_PUBLIC_STREAM_KEEPER_ADDRESS=${streamKeeper.address}`,
    `NEXT_PUBLIC_STREAM_FACTORY_ADDRESS=${streamFactory.address}`,
    `NEXT_PUBLIC_CHAIN_ID=${hre.network.config.chainId}`,
    `NEXT_PUBLIC_RPC_URL=https://dream-rpc.somnia.network`,
    `NEXT_PUBLIC_BLOCK_EXPLORER=https://shannon-explorer.somnia.network`,
  ].join("\n");

  writeFileSync(envLocalPath, envContent, "utf8");
  console.log("📄 Frontend .env.local updated:", envLocalPath);
  console.log("   → Restart the Next.js dev server to pick up new addresses.\n");

  // ─── Write deployment artifact ────────────────────────────────────────────
  const artifactsDir = join(__dirname, "../deployments");
  if (!existsSync(artifactsDir)) mkdirSync(artifactsDir);
  writeFileSync(
    join(artifactsDir, `${hre.network.name}-${Date.now()}.json`),
    JSON.stringify(deploymentData, null, 2),
    "utf8"
  );
  console.log("📦 Deployment artifact saved to contracts/deployments/\n");
}

main().catch((err) => {
  console.error("\n❌ Deployment failed:\n", err.message || err);
  process.exit(1);
});
